crud_minsa/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('paciente.urls')),
]

paciente/urls.py
from django.contrib import admin
from django.urls import path
from paciente.views import ListarPaciente,BuscarPaciente
from .views import Paciente_new
from . import views
urlpatterns = [
    path('ingresar_paciente',views.Paciente_new,name='paciente_new'),
    path('listar_paciente', ListarPaciente.as_view(), name='listar_paciente'),
   # path('listar_paciente', PacienteListView.as_view(), name='listar_paciente'),
    path('buscar_paciente', views.BuscarPaciente, name='buscar_paciente'),
    path('editar_paciente/<int:pk>', views.Paciente_editar),
    path('eliminar_paciente/<int:pk>', views.Paciente_eliminar),
]

paciente/models.py
from django.db import models
from datetime import datetime,date
from dateutil.relativedelta import relativedelta
# Create your models here.


class Paciente(models.Model):
    tipdoc=(('1', 'DNI'),('2', 'Carnet de Extranjeria'),('3','Indocumentado'))
    tipo_documento=models.CharField(max_length=1,choices=tipdoc)
    numero_documento=models.CharField(max_length=15,blank=False)
    nombres=models.CharField(max_length=45)
    apellido_paterno=models.CharField(max_length=30)
    apellido_materno=models.CharField(max_length=30)
    fecha_nacimiento=models.DateField()

    class Meta:
        unique_together = ('tipo_documento', 'numero_documento')

    @property
    def edad(self):
        edad1=relativedelta(datetime.now().date(), self.fecha_nacimiento)
        if edad1.years < 1:
            if edad1.months < 0:
                resultado = '{day} días'.format(day=edad1.days)
            else:
                resultado = '{month} meses {day} días'.format(month=edad1.months,day=edad1.days)
        else:
            resultado = '{year} años {month} meses {day} días'.format(year=edad1.years,month=edad1.months, day=edad1.days)

        return resultado

    @property
    def tip_doc(self):
        tipdoc = [('1', 'DNI'), ('2', 'Carnet de Extranjeria'), ('3', 'Indocumentado')]
        for i in range(0,2):
            if tipdoc[i][0] == self.tipo_documento:
                return tipdoc[i][1]

    def __str__(self):
        return self.nombres
    @property
    def nombre_completo(self):
        return '{nombres} {ape_paterno} {ape_materno}'.format(
            nombres = self.nombres or '',
            ape_paterno = self.apellido_paterno or '',
            ape_materno = self.apellido_materno or '',
        )

paciente/forms.py
from django.views.generic import  ListView
from django import forms
from django.shortcuts import render
from .models import Paciente

class PacienteForm(forms.ModelForm):

    class Meta:
        model = Paciente
        fields = [
            'tipo_documento',
            'numero_documento',
            'nombres',
            'apellido_paterno',
            'apellido_materno',
            'fecha_nacimiento',

            ]

        widgets = {
            'tipo_documento': forms.Select(attrs={'class': 'custom-select custom-select-lg mb-1'}),
            'numero_documento':forms.TextInput(attrs={'class':'form-control'}),
            'nombres': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido_paterno': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido_materno': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento':forms.DateInput(attrs={'placeholder': 'dd-MM-yyyy','class': 'form-control'}),

        }

class BuscarPaciente(forms.ModelForm):
    tipdoc = (('1', 'DNI'), ('2', 'Carnet de Extranjeria'), ('3', 'Indocumentado'))
    class Meta:
        model = Paciente
        fields = [
            'tipo_documento',
            'numero_documento',
        ]
        tipdoc = (('1', 'DNI'), ('2', 'Carnet de Extranjeria'), ('3', 'Indocumentado'))
        widgets = {
            'tipo_documento': forms.Select(attrs={'class': 'custom-select custom-select-lg mb-1'}),
            'numero_documento': forms.TextInput(attrs={'class': 'form-control'}),

        }

paciente/views.py
from django.views.generic import ListView, FormView, CreateView, UpdateView
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from .models import Paciente
from .forms import PacienteForm, BuscarPaciente
from django.utils import timezone

# Create your views here.


class ListarPaciente(ListView, FormView):
    template_name = 'listar_paciente.html'
    queryset = Paciente.objects.all()
    model = Paciente
    context_object_name = 'paciente'
    form_class = BuscarPaciente
    form = BuscarPaciente

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        form.is_valid()
        enc = False
        tipo_documento = form.cleaned_data.get('tipo_documento')
        numero_documento = form.cleaned_data.get('numero_documento')
        try:
            paciente = Paciente.objects.get(tipo_documento=tipo_documento,numero_documento=numero_documento)
            if paciente != '':
                return render(request, "listar_paciente.html", {'form': form, 'enc': enc, 'paciente': paciente})
        except:
            enc = True
            return render(request, "listar_paciente.html", {'form': form, 'enc': enc})


def Paciente_new(request):
    enc1 = 0
    if request.method == "POST":
        form = PacienteForm(request.POST)
        enc1 = 1
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('listar_paciente')
    else:
        form = PacienteForm()
    return render(request, 'formulario1.html', {'form': form,'enc1':enc1})


def Paciente_editar(request, pk):
    post = get_object_or_404(Paciente, pk=pk)
    if request.method == "POST":
        form = PacienteForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('listar_paciente')  # pk=post.pk
    else:
        form = PacienteForm(instance=post)
    return render(request, 'formulario1.html', {'form': form})


def Paciente_eliminar(request, pk):
    paciente = Paciente.objects.get(id=pk)
    if request.method == 'POST':
        paciente.delete()
        return redirect('listar_paciente')
    return render(request, 'eliminar_paciente.html', {'paciente': paciente})

paciente/templates/base.html

<!DOCTYPE html>
{% load staticfiles %}
    <html>
        <head>
            <meta charset="utf-8">
            <meta http-equiv="Content-Type" content="text/html; charset=gb18030">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

            <title>Ingresar Paciente</title>
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
            <script src="{% static 'js/formulario1.js' %}"></script>
            <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
            <script src="{% static 'js/jquery-ui.js' %}"></script>
            <script src="{% static 'js/jquery-1.9.1.min.js' %}"></script>

            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
            <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

        </head>
        <body>

            <div class="content container">
                <div class="row">
                    <div class="col-md-8">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

paciente/templates/eliminar_paciente.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de:  {{ paciente.nombres}} {{ paciente.apellido_paterno}} {{ paciente.apellido_materno}}</h3>
    <button class="btn btn-danger"  type="submit">Sí Eliminar</button>
    <a class="btn btn-default" href="../listar_paciente">Cancelar</a>


</form>

{% endblock content %}

paciente/templates/formulario1.html
{% extends 'base.html' %}


{% block content %}

     <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
<script>
$(document).ready(function() {
$(".alert").hide();fec1=$("#id_fecha_nacimiento").val();
if($("#msg1").html()>0){$("#malertf").show();$("#malertf").delay(3200).fadeOut(10);}
 $("#edad").val(calculaedad1(fec1));
$("#id_fecha_nacimiento").datepicker({format: 'dd/mm/yyyy (D)',language: 'es'}).on("change", function(e) {
fec1=$("#id_fecha_nacimiento").val();
 $("#edad").val(calculaedad1(fec1));
});

$("#id_fecha_nacimiento").blur(function() {
fec1=$("#id_fecha_nacimiento").val();
 $("#edad").val(calculaedad1(fec1));
 });

	});
</script>


<br>
  <div class="p-1 container border rounded bg-white shadow-sm" style="box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.10);">
 <div class="p-3"> <h6><font class="text-info">INGRESA Y/O EDITA INFORMACION DE PACIENTE</font></h6></div>


  <form class="form-horizontal" method="POST" id="id_form">{% csrf_token %}
      <div class="alert alert-danger" role="alert" id="malertf">
<strong>Error!</strong> Ya existe el tipo y número de documento.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

   <div class="row container ">
        <div class="col-sm ">
        <label class="control-label small" ><i class="fas fa-bug"></i><strong> TIPO DE DOCUMENTO</strong></label>
        {{ form.tipo_documento }}
     </div>
     <div class="col-sm ">
        <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> NUMERO DE DOCUMENTO</strong></label>
           {{ form.numero_documento }}
    </div>
       <div class="row container ">
       <div class="col-sm">
        <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> NOMBRES</strong></label>
           {{ form.nombres }}
    </div>
     <div class="col-sm ">
        <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> APELLIDO PATERNO</strong></label>
           {{ form.apellido_paterno }}
    </div>
       </div>
        <div class="row container ">
       <div class="col-sm ">
        <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> APELLIDO MATERNO</strong></label>
           {{ form.apellido_materno }}
    </div>
     <div class="col-sm ">
        <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> FECHA DE NACIMIENTO</strong></label>
           {{ form.fecha_nacimiento }}
    </div>
       </div>
    <div class="row container ">
    <div class="col-sm-6">
        <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> EDAD</strong></label>
        <input type="unidadmedida" class="form-control  col-sm-40 " id="edad" value=""  readonly >
    </div>
     <div class="col-sm ">
       <div class="row">
        <div class="col-md">
        </div>
        </div>
    </div>
    </div>


     <div class="alert alert-success" role="alert" id="malertm">
<strong>Modificado!</strong> Los datos fueron modificados correctamente.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
       <div><br><br></div>
    <div class="row container ">
        <div class="col-sm ">
   <button type="submit"  class="btn btn-info" onclick="" id="guardar" value="GUARDAR"><span class="fas fa-save"></span> GUARDAR</button>
            {% if enc1 > 0 %}
            <div id="msg1" style="display:none;visibility:hidden;">{{enc1}}</div>
            {% endif %}
   </div>
    </div>
<div><br></div>
     <div class="row container ">

     <div class="col-sm " id="mostrarb">
     <input type="hidden"  id="med">

     </div>

    </div>


  </form>

</div>




<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
        <input type="hidden" class="form-control" id="idpersona" placeholder="">
      </div>
    </div>
  </div>
</div>





        </div>
    </div>
{% endblock %}

paciente/templates/listar_paciente.html
{% extends 'base.html' %}

{% block content %}


 <div class="p-1 container border rounded bg-white shadow-sm" style="box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.10);">
 <div class="p-3"> <h6><font class="text-info">BUSCAR PACIENTE</font></h6></div>

<form class="form-horizontal" method="POST" id="id_form">{% csrf_token %}

      <div class="alert alert-danger" role="alert" id="malertf">
<strong>Error!</strong> Faltan llenar datos.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

    <br>
    <form method="post" action="" class="form">
        <div class="container">
      {% csrf_token %}
      <div class="row">
        <div class="col-sm">
            <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> TIPO DE DOCUMENTO</strong></label>
             {{ form.tipo_documento}}
        </div>
        <div class="col-sm">
            <label class="control-label small" ><i class="fas fa-briefcase"></i><strong> NUMERO DE DOCUMENTO</strong></label>
            {{ form.numero_documento}}
        </div>
        <div class="col-sm">
            <label class="control-label small" ><i class="fas fa-briefcase"></i><strong>&nbsp;</strong></label>
            <div></div>
            <button type="submit"  class="btn btn-info" onclick="" id="guardar" value="GUARDAR"><span class="fas fa-save"></span> BUSCAR</button>
               <a class="btn btn-info" href="ingresar_paciente">CREAR PACIENTE</a>
        </div>
      </div>
        </div>
    </form>

<br>
<table class="table">

  <thead class="thead-dark">
    <tr>
      <th scope="col">Tipo de documento</th>
      <th scope="col">Numero de documento</th>
      <th scope="col">Fecha de Nacimiento</th>
      <th scope="col">Edad</th>
      <th scope="col">Nombres y Apellidos</th>
      <th scope="col">Gestionar Paciente</th>
    </tr>
  </thead>
        {% if enc %}
                   <td> <span class="menu-title">No se encontraron resultados</span></td>
        {% endif %}
        {% if paciente.id %}
    <tr>

                   <td> <span class="menu-title">{{ paciente.tip_doc }}</span></td>
                   <td> <span class="menu-title">{{ paciente.numero_documento }}</span></td>
                   <td> <span class="menu-title">{{ paciente.fecha_nacimiento }}</span></td>
                   <td> <span class="menu-title">{{ paciente.edad }}</span></td>
                   <td> <span class="menu-title">{{ paciente.nombre_completo }}</span></td>
        <td>
                 <a class="btn btn-default" href="editar_paciente/{{ paciente.id }}"><span class="glyphicon glyphicon-pencil">Editar</span></a>
                 <a class="btn btn-default" href="eliminar_paciente/{{ paciente.id }}"><span class="glyphicon glyphicon-trash">Eliminar</span></a>
                </td>

    </tr>
        {% endif %}
            	<tbody>
                   {% for value in object_list %}
            <tr>
                <td> <span class="menu-title">{{ value.tip_doc }}</span></td>
                <td> <span class="menu-title">{{ value.numero_documento }}</span></td>
                <td> <span class="menu-title">{{ value.fecha_nacimiento }}</span></td>
                <td> <span class="menu-title">{{ value.edad }}</span></td>
                <td> <span class="menu-title">{{ value.nombre_completo }}</span></td>
                <td>
                 <a class="btn btn-default" href="editar_paciente/{{ value.id }}"><span class="glyphicon glyphicon-pencil">Editar</span></a>
                 <a class="btn btn-default" href="eliminar_paciente/{{ value.id }}"><span class="glyphicon glyphicon-trash">Eliminar</span></a>
                </td>
            </tr>
             {% endfor %}
            </tbody>

</table>

<script>

$(document).ready(function() {
$(".alert").hide();
fec1=$("#fecnac").html();
var ano1=fec1.getYear();alert(22);
 //$("#edad").html(calculaedad1(fec1));


	});


</script>


{% endblock %}